development:
  adapter: postgresql
  encoding: unicode
  database: todo_app_rails_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: todo_app_rails_test
  pool: 5
  host: localhost
